# Generated by Django 4.2.29 on 2026-06-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.IntegerField(db_column='activo', default=1)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('id_contratacion', models.AutoField(db_column='id_contratacion', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='fecha_programada', null=True)),
                ('fecha_solicitud', models.DateField(blank=True, db_column='fecha_solicitud', null=True)),
                ('estado', models.CharField(db_column='estado_contratacion', max_length=255)),
                ('observacion', models.TextField(blank=True, db_column='observacion', null=True)),
            ],
            options={
                'db_table': 'contratacion',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(db_column='id_metodo_pago', primary_key=True, serialize=False)),
                ('forma_pago', models.CharField(db_column='forma_pago', max_length=255)),
            ],
            options={
                'db_table': 'metodos_pago',
            },
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id_prestador', models.AutoField(db_column='id_prestador', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('dias_atencion', models.CharField(blank=True, db_column='dias_atencion', max_length=255, null=True)),
                ('horario_atencion', models.CharField(blank=True, db_column='horario_atencion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'prestadores',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('rol', models.CharField(db_column='rol', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
                ('reset_token', models.CharField(blank=True, db_column='reset_token', max_length=255, null=True)),
                ('foto_perfil', models.CharField(blank=True, db_column='foto_perfil', max_length=255, null=True)),
                ('activo', models.IntegerField(db_column='activo', default=1)),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, to='core.rol')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(db_column='id_servicio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio_min', models.FloatField()),
                ('precio_max', models.FloatField()),
                ('activo', models.IntegerField(db_column='activo', default=1)),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, to='core.categoria')),
                ('prestador', models.ForeignKey(db_column='id_prestador', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.prestador')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='PrestadorCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('prestador', models.ForeignKey(db_column='id_prestador', on_delete=django.db.models.deletion.CASCADE, to='core.prestador')),
            ],
            options={
                'db_table': 'prestador_categoria',
                'unique_together': {('prestador', 'categoria')},
            },
        ),
        migrations.AddField(
            model_name='prestador',
            name='categorias',
            field=models.ManyToManyField(related_name='prestadores', through='core.PrestadorCategoria', to='core.categoria'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expiration', models.DateTimeField()),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'password_reset_token',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(db_column='id_pago', primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('fecha', models.DateField(db_column='fecha_pago')),
                ('contratacion', models.ForeignKey(db_column='id_contratacion', on_delete=django.db.models.deletion.PROTECT, to='core.contratacion')),
                ('metodo', models.ForeignKey(db_column='id_metodo_pago', on_delete=django.db.models.deletion.PROTECT, to='core.metodopago')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.AddField(
            model_name='contratacion',
            name='prestador',
            field=models.ForeignKey(db_column='id_prestador', on_delete=django.db.models.deletion.PROTECT, to='core.prestador'),
        ),
        migrations.AddField(
            model_name='contratacion',
            name='servicio',
            field=models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.PROTECT, to='core.servicio'),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(db_column='id_calificacion', primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.TextField()),
                ('contratacion', models.ForeignKey(db_column='id_contratacion', on_delete=django.db.models.deletion.PROTECT, to='core.contratacion')),
                ('prestador', models.ForeignKey(db_column='id_prestador', on_delete=django.db.models.deletion.PROTECT, to='core.prestador')),
            ],
            options={
                'db_table': 'calificacion',
            },
        ),
        migrations.CreateModel(
            name='ClienteContratacion',
            fields=[
                ('contratacion', models.OneToOneField(db_column='id_contratacion', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.contratacion')),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'cliente_contratacion',
                'unique_together': {('cliente', 'contratacion')},
            },
        ),
        migrations.CreateModel(
            name='ClienteCalificacion',
            fields=[
                ('calificacion', models.OneToOneField(db_column='id_calificacion', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.calificacion')),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'cliente_calificacion',
                'unique_together': {('cliente', 'calificacion')},
            },
        ),
    ]
